### ISSUE TITLE
WP CLI command doesn't seem to respect the correct database prefix

### ISSUE THREAD

**Issue by uprise10** [GlotPress/GlotPress#578] opened 2016-10-11 17:13 UTC
When using the "import-originals" command for WP-CLI for a specific site in a multisite setup, the queries that are used (for selecting the project for example) are just using the prefix of the main site (`wp_gp_projects`) instead of the prefix of the chosen site (`wp_26_gd_projects`).

This is the command that I'm using:
`wp glotpress import-originals my-project current/app/www/content/themes/my-theme/languages/walraven.pot --url=my-website.domain.dev`

Where `my-website.domain.dev` has blog_id 26.

The error that is shown is:

> WordPress database error Table 'uprisedev.wp_gp_projects' doesn't exist for query SELECT \* FROM wp_gp_projects WHERE path = 'my-project' made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher{closure}, call_user_func, GP_CLI_Import_Originals->__invoke, GP_Project->by_path, GP_Thing->one
> Error: Project not found!

As you can see the table prefix is just `wp_` instead of `wp_26_`

FYI: when enabling the glotpress plugin in the main site, the above command just works great.

**Comment by KingYes** [comment] 2016-12-26 14:49
Any news about this bug?

**Comment by toolstack** [comment] 2016-12-26 16:37
It looks like a bug in WP-CLI, we use the `$GLOABLS['table_prefix']` value to define the table names but WP-CLI doesn't seem to update this after it processes the `--url` parameter.

Try editing your gp-settings.php (in the gp plugin directory), line 21 should be:

`
	$gp_table_prefix = $GLOBALES['table_prefix'] . 'gp_';
`

change it to:

`
	$gp_table_prefix = $wpdb->prefix . 'gp_';
`

and see if that works.

**Comment by KingYes** [comment] 2016-12-26 17:10
For now I just write this code before I call any method from GP.

```
global $wpdb;

\GP::$project->table = $wpdb->prefix . \GP::$project->table_basename;
\GP::$original->table = $wpdb->prefix . \GP::$original->table_basename;
```

**Comment by toolstack** [comment] 2016-12-26 17:20
If you try the above fix I posted and confirm it works we'll get it in to the next release.

**Comment by toolstack** [comment] 2016-12-28 21:19
I've submitted an [issue](https://github.com/wp-cli/wp-cli/issues/3694) to the WP-CLI project and they've confirmed a bug in their code, it will be fixed in the next release of WP-CLI.

**Comment by KingYes** [comment] 2016-12-28 21:30
Nice, thanks! :)

**Comment by ocean90** [comment] 2017-02-01 18:36
[WP-CLI 1.1.0 has been released](https://make.wordpress.org/cli/2017/02/01/version-1-1-0/) and includes a fix for this issue.

**Closed as completed by ocean90** 2017-02-01 18:36 UTC
Labels: [Type] Bug, [Status] Invalid
