### ISSUE TITLE
Simplify formal and informal translation (e.g. German) with copy function

### ISSUE THREAD

**Issue by e-colori** [GlotPress/GlotPress#590] opened 2016-10-30 12:40 UTC
In German the translation for formal and informal German are often the same.
e.g. "Usage" > "Verwendung"
It would be very useful if there would exist a checkbox "[  ] same translation for German (formal)" and this function copies the string to the formal translation.
This would save a lot of time because many string are the same in both!

**Comment by Zodiac1978** [comment] 2016-10-30 13:09
First mentioned here: https://glotpress.trac.wordpress.org/ticket/432

**Comment by toolstack** [comment] 2016-10-30 14:13
Duplicate of #226.

**Comment by chantalcoolsma** [comment] 2016-12-06 09:14
> It would be very useful if there would exist a checkbox "[ ] same translation for German (formal)" and this function copies the string to the formal translation.

What about the strings which needs a change to the formal state? Those aren't copied? If string is the same, it could be copied and set to waiting/approved. If the string needs a change, it could be set to fuzzy.

This could also work the other way. So if someone translates the formal string and want to copy the string to the non-formal version.

**Comment by Zodiac1978** [comment] 2018-01-13 12:57
Like mentioned in https://glotpress.trac.wordpress.org/ticket/432 this could be more flexible: We could copy from other locales too (imagine copying from `es_ES` to `es_CO` instead of copy from `de_DE` to `de_DE-informal`.

**Comment by toolstack** [comment] 2018-01-13 18:06
See the variants isssue #226 and PR #747 which address much of this.

**Comment by michakrapp** [comment] 2018-10-10 10:02
I think it would be better to reverse the original idea.

When (local variants #226 is ready and) you edit a translation for a variant (ie. german formal) there could be a new link beside "Copy from original" named "Copy from parent variant" or something like that which copies the translation from the parent variant (ie. german).

Then you could easily save it or adjust the words for the variant.

**Comment by toolstack** [comment] 2018-10-10 16:02
The variants PR above simplifies the entire process by inheriting all strings from the parent and presenting them as if they were part of the variant.  That way, as the parent translations change, they are automatically inherited by the variant.  Simply modifying any of the inherited translations creates them in the variant so that they are no longer inherited.

Closing this ticket as it is really part of #226.

**Closed as completed by toolstack** 2018-10-10 16:02 UTC
