### ISSUE TITLE
Add feature: Import as Waiting

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress#520] opened 2016-08-04 14:50 UTC
People provide us with translations made in other Tools (like PoEdit).

Now a translation editor have to import these po files.

Two problems here:
- translation editor gets all the credits
- all translations are approved

Maybe we can add a new option: **import as waiting**, so translation editors can import translations and the approving can be made by all translation editors together.

**Comment by ocean90** [comment] 2016-08-04 15:10
Duplicate of #377.

**Closed as completed by ocean90** 2016-08-04 15:10 UTC
Labels: [Status] Duplicate
